---
title: "COMPSCIX 415.2 Homework 1"
author: "Yukio Rattai"
date: "1/30/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## My Github repository for my assignments can be found at this URL: [https://github.com/Ukeeyo/compscix4152]

### There are 10 variables and 23,018 observations
```{r load_packages, warning=FALSE, message=FALSE}
library(mdsr)
library(tidyverse)
data("WorldCities")

glimpse(WorldCities)
```

### Unique countries
```{r}
WorldCities <- head(WorldCities, 200)
country_col <- WorldCities$country

unique(country_col)
```

### Unique regions
```{r}
region_col <- WorldCities$region
unique(region_col)
```


### Unique countries one linear

```{r}
WorldCities %>% select(country) %>% unique()
```


### Visualize

```{r}
WorldCities %>% ggplot(aes(x = population)) + geom_histogram()
```

### Visualized w/labels and black and white theme!
```{r}
plot <- WorldCities %>% ggplot(aes(x = population)) + geom_histogram()
plot + ggtitle('Population Graph Title!') + theme_bw(base_size = 11, base_family = "")
```
